---
# https://taskfile.dev

version: '3'

includes:
  py:
    taskfile: ./goat/Task/python/Taskfile.yml
    internal: true
    vars:
      INPUT_DISABLE_MYPY: "true"
      INPUT_EXCLUDE: .*\{\{.*\}\}.*
      PROJECT_SLUG: cookiecutter-python
      PYTHON_VERSION: 3.11

silent: true

tasks:
  lock:
    internal: true
    sources:
      - Pipfile
    generates:
      - Pipfile.lock
    cmds:
      - pipenv lock

  init:
    deps: [lock]
    sources:
      - Pipfile.lock
    cmds:
      - git submodule init
      - pipenv install --deploy --ignore-pipfile --dev
      - pipenv run pre-commit install

  lint:
    cmds:
      - task: py:lint

  test:
    cmds:
      - pipenv run pytest --keep-baked-projects tests

  update:
    cmds:
      - task: py:update

  clean:
    cmds:
      - task: py:clean

  release:
    deps: [test]
    cmds:
      - task: py:release
