# https://taskfile.dev

version: '3'

includes:
  py: 
    taskfile: ./goat/Task/python/Taskfile.yml
    internal: true
    vars:
      IMAGE_NAME: seiso/{{ cookiecutter.project_slug }}
      PROJECT_SLUG: {{ cookiecutter.project_slug }}
      PYTHON_VERSION: {{ cookiecutter.python_version }}

silent: true

tasks:
  lock:
    internal: true
    sources:
      - Pipfile
    generates:
      - Pipfile.lock
    cmds:
      - pipenv lock

  init:
    deps: [lock]
    sources:
      - Pipfile.lock
    cmds:
      - git submodule init
      - pipenv install --deploy --ignore-pipfile --dev

  lint:
    cmds:
      - task: py:lint

  test:
    cmds:
      - task: py:test

  build:
    cmds:
      - task: py:build

  update:
    cmds:
      - task: py:update

  clean:
    cmds:
      - task: py:clean

  release:
    cmds:
      - task: py:release
{%- if cookiecutter.dockerhub == 'yes' %}

  publish:
    cmds:
      - task: py:publish
{%- endif %}
