# https://taskfile.dev

version: '3'

includes:
  py: 
    taskfile: ./goat/Task/python
    internal: true
    vars:
      IMAGE_NAME: seiso/{{ cookiecutter.project_slug }}
      PROJECT_SLUG: {{ cookiecutter.project_slug }}
      PYTHON_VERSION: {{ cookiecutter.python_version }}

silent: true

tasks:
  init:
    cmds:
      - git submodule update --init --recursive
      - pipenv install --deploy --ignore-pipfile --dev

  lint:
    cmds:
      - task: py:lint

  test:
    cmds:
      - task: py:test

  build:
    cmds:
      - task: py:build

  reformat:
    cmds:
      - task: py:reformat

  update:
    cmds:
      - task: py:update

  clean:
    cmds:
      - task: py:clean

  release:
    cmds:
{%- if cookiecutter.versioning == 'SemVer-ish' %}
      - task: py:release-semver
{%- elif cookiecutter.versioning == 'CalVer' %}
      - task: py:release-calver
{%- endif %}
{%- if cookiecutter.dockerhub == 'yes' %}

  publish:
    cmds:
      - task: py:publish
{%- endif %}
