---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
{%- for python_version in cookiecutter.python_versions %}
          - {{ python_version }}
{%- endfor %}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the goat
        uses: seisollc/goat@main
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ "{{ matrix.python-version }}" }}
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ matrix.python-version }}" }} --dev
      - name: Run the tests
        run: pipenv run invoke test
{%- if cookiecutter.dockerhub == 'y' %}
  distribute:
    name: Distribute
    if: ${{ "{{ github.event_name == 'push' }}" }}
    runs-on: Ubuntu-20.04
    needs: test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: {{ cookiecutter.python_versions[0] }}
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
      - name: Publish the README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
          repository: seiso/{{ cookiecutter.project_slug }}
          short-description: {{ cookiecutter.project_short_description }}
      - name: Publish the latest docker image
        run: pipenv run invoke publish latest
{%- endif -%}
