---
name: "PR"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
{%- for python_version in cookiecutter.python_versions %}
          - {{ python_version }}
{%- endfor %}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ "{{ github.event.pull_request.head.sha }}" }}
      - name: Run the goat
        uses: seisollc/goat@main
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ "{{ matrix.python-version }}" }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ matrix.python-version }}" }} --dev
      - name: Run the tests
        run: pipenv run invoke test
