---
name: "Publish a release"
on:
  push:
    tags:
{%- if cookiecutter.versioning == "SemVer-ish" %}
      - 'v[0-9]+.[0-9]+.[0-9]-(\+[0-9a-f]{5,10})?'
{%- elif cookiecutter.versioning == "CalVer" %}
      - 'v2[0-1][0-9]{2}.(0[0-9]|1[0-2])_[0-9]{2}(\-[0-9a-f]{5,10})?'
{%- endif %}

jobs:
  publish:
    name: Publish versioned artifacts
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ python-version }}" }} --dev
      - name: Publish the release to GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ "{{ secrets.GITHUB_TOKEN }}" }}
        with:
          tag_name: ${{ "{{ github.ref }}" }}
          release_name: ${{ "{{ github.ref }}" }} release
          draft: false
          prerelease: false
{%- if cookiecutter.dockerhub == 'y' %}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
      - name: Publish the README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
          repository: seiso/{{ cookiecutter.project_slug }}
          short-description: {{ cookiecutter.project_short_description }}
      - name: Publish the release to Docker Hub
        run: pipenv run invoke publish release
{%- endif -%}
