---
name: "Release"
on:
  push:
    tags:
      - 'stable'
jobs:
  release:
    name: Release versioned artifacts
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - '3.9'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ "{{ matrix.python-version }}" }}
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ matrix.python-version }}" }} --dev
      - name: Create the release
        run: |
          pipenv run invoke release
      - name: Publish a release to GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ "{{ secrets.GITHUB_TOKEN }}" }}
        with:
          tag_name: ${{ "{{ github.ref }}" }} # TODO: If we move this from a tag push...
          release_name: Release ${{ "{{ github.ref }}" }}
          draft: false
          prerelease: false
{%- if cookiecutter.dockerhub == 'y' %}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          password: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
      - name: Publish the README
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8
        env:
          DOCKER_USER: ${{ "{{ secrets.DOCKERHUB_USERNAME }}" }}
          DOCKER_PASS: ${{ "{{ secrets.DOCKERHUB_TOKEN }}" }}
        with:
          destination_container_repo: seiso/{{ cookiecutter.project_slug }}
          provider: dockerhub
          short_description: {{ cookiecutter.project_short_description }}
          readme_file: README.md
      - name: Publish the image's versioned tag to Docker Hub
        run: pipenv run invoke publish version
{%- endif -%}
