---
name: "Security"

on:
{%- if cookiecutter.public == 'yes' %}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '{{ range(0, 59) | random }} {{ range(2, 4) | random }} * * *'
{%- elif cookiecutter.public == 'no' %}
  - workflow_dispatch
{%- endif %}

jobs:
  analyze:
    name: CodeQL
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version:
{%- for python_version in cookiecutter.python_versions %}
          - {{ python_version }}
{%- endfor %}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ "{{ matrix.python-version }}" }}
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ matrix.python-version }}" }} --dev
          echo "CODEQL_PYTHON=$(pipenv run which python)" >> "${GITHUB_ENV}"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
