---
name: "Update"

on:
  schedule:
    - cron: '{{ range(0, 59) | random }} {{ range(2, 4) | random }} * * 1,4'

jobs:
  update:
    name: Update
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "{{ cookiecutter.python_versions[0] }}"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy --ignore-pipfile --dev
      - name: Update the repository
        run: pipenv run invoke update
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated update to primary components
          commit-message: Automated update to primary components
          committer: Seiso Automation <automation@seisollc.com>
          delete-branch: true
          signoff: true
