---
name: "Update"

on:
  schedule:
    - cron: '{{ range(0, 59) | random }} {{ range(2, 4) | random }} * * 1,4'
  workflow_dispatch:

env:
  python_version: "{{ cookiecutter.python_version }}"

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ "{{ env.python_version }}" }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ "{{ runner.os }}" }}-python-${{ "{{ env.python_version }}" }}-pipenv-${{ "{{ hashFiles('Pipfile.lock') }}" }}
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Initialize the repo
        run: task -v init
      - name: Update the repository
        run: task -v update
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated update to primary components
          commit-message: Automated update to primary components
          committer: Seiso Automation <automation@seisollc.com>
          delete-branch: true
          signoff: true
