---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 5 * * 0'

jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the goat
        uses: seisollc/goat@main
        with:
          # Exclude anything that contains {{ and }} in the file name
          exclude: .*\{\{.*\}\}.*
          disable_mypy: true
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Run the tests
        run: pipenv run invoke test --debug
