---
name: "Commit"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.9
          - 3.10
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ "{{ matrix.python-version }}" }}
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ "{{ matrix.python-version }}" }} --dev
      - name: Run the tests
        run: pipenv run invoke test
