---
name: "Release"

on:
  push:
    tags:
      - 'v2[0-1][0-9][0-9].0[0-9].[0-9][0-9]'
      - 'v2[0-1][0-9][0-9].1[0-2].[0-9][0-9]'

jobs:
  distribute:
    name: Distribute
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Publish the release to GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} release
          draft: false
          prerelease: false
